<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Smoke" duration-ms="45667" started-at="2019-03-29T06:25:53Z" finished-at="2019-03-29T06:26:39Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="45667" started-at="2019-03-29T06:25:53Z" finished-at="2019-03-29T06:26:39Z">
      <class name="multithreading.AuthenticationTest">
        <test-method status="FAIL" signature="userIsAbleToAuthenticateSuccessfullyJira001(java.lang.String)[pri:0, instance:multithreading.AuthenticationTest@59ec2012]" name="userIsAbleToAuthenticateSuccessfullyJira001" duration-ms="44197" started-at="2019-03-29T06:25:53Z" data-provider="getBrowsers" finished-at="2019-03-29T06:26:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at multithreading.TestBase.testFailed(TestBase.java:74)
at multithreading.AuthenticationTest.userIsAbleToAuthenticateSuccessfullyJira001(AuthenticationTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userIsAbleToAuthenticateSuccessfullyJira001 -->
        <test-method status="FAIL" signature="userIsAbleToAuthenticateSuccessfullyJira001(java.lang.String)[pri:0, instance:multithreading.AuthenticationTest@59ec2012]" name="userIsAbleToAuthenticateSuccessfullyJira001" duration-ms="45611" started-at="2019-03-29T06:25:53Z" data-provider="getBrowsers" finished-at="2019-03-29T06:26:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at multithreading.TestBase.testFailed(TestBase.java:74)
at multithreading.AuthenticationTest.userIsAbleToAuthenticateSuccessfullyJira001(AuthenticationTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userIsAbleToAuthenticateSuccessfullyJira001 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:multithreading.AuthenticationTest@59ec2012]" name="tearDown" is-config="true" duration-ms="227" started-at="2019-03-29T06:26:37Z" finished-at="2019-03-29T06:26:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:multithreading.AuthenticationTest@59ec2012]" name="tearDown" is-config="true" duration-ms="39" started-at="2019-03-29T06:26:39Z" finished-at="2019-03-29T06:26:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- multithreading.AuthenticationTest -->
    </test> <!-- Test -->
  </suite> <!-- Smoke -->
</testng-results>
